name: Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format
      
    - name: Check formatting
      run: |
        find include src tests examples -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file -i
        git diff --exit-code
      continue-on-error: true
      
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy cmake ninja-build
        
    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
    - name: Run clang-tidy
      run: |
        find include src -name "*.cpp" -o -name "*.h" | xargs clang-tidy -p build
      continue-on-error: true
      
  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --std=c++20 --error-exitcode=1 --suppress=missingIncludeSystem src include
      continue-on-error: true 